return {
'                                    ',
'              ..                    ',
'          x+~WMW^Xx+x.              ',
'       .X^WMW.o~~.oxW^^X.           ',
'      /WM.~^       ^.MWM^x          ',
'      X==X           X.WM;X         ',
'      `MW^.          ^XMWM^;        ',
'       `WM;.          XWMX^         ',
'      .~_.o;         .^W.^          ',
'   .;^^=+=^;.      ;^M.^            ',
' .X^=+ ~ + W^.    .^WM;             ',
' O;=+ ~ ~ + W;;   ;.MW;             ',
' ^Xx=+ ~ +=+xX     ;.MW^X.          ',
'   O;+=+=+;OO       ^XMWM^^^`       ',
'    ^^~~~^^           ^~WWWW~/      ',
'                                    ',
'                                    ' }
