return {
'                                    ',
' ..oo    ..      ..                 ',
'   ^OOO..ooo.  .ooo..               ',
'     ;/OOO^^OMMO^^OOO`              ',
'     ;+O^   ^OO^   ^O+              ',
'      WW;   ;MM;   ;WW              ',
'      M+;   ;++;   ;+M              ',
'      WW;   ;MM;   ;WW              ',
'      MM;   ;++;   ;MM              ',
'      W+;   ;WW;   ;+W              ',
'      MM;   ;++;   ;MM              ',
'      WW;   ;WW;   ;MM              ',
'      ^^     ^^    ;WW.      .      ',
'                   ;WWW+.....;=.    ',
'                    ^W+W+W+W+W+++   ',
'                       ^^^^^^;=^    ',
'                             ^      ',
'                                    '}

