return {
'                                    ',
' ..oo    ..      ..                 ',
'   ^OOO..ooo.  .ooo..               ',
'     ;/OOO^^OMMO^^OOO`              ',
'     ;+O^   ^OO^   ^O+  ..          ',
'      WW;   ;MM;   ;WW .OOO.        ',
'      M+;   ;++;   ;+MO;^;.OO^.     ',
'      WW;   ;MM;   ;WW^    `OOO;.   ',
'      MM;   ;++;   ;MM      `OOO;   ',
'      W+;   ;WW;   ;+W       OO;^   ',
'      MM;   ;++;   ;MM    ./OO^     ',
'      WW;   ;WW;   .MM.oOO;^^       ',
'      ^^     ^^ ./OOOOOOO^^         ',
'                    +MM.            ',
'                     +W+WW.         ',
'                       +M+M+M.      ',
'                           ^^^^     ',
'                                    '}
