Aries = { Name = "Aries",
    Unicode = "\u{2648}",
    Start_Day = "20", 
    Start_Mon = "03", 
    Starts = "March 20",
    End_Day = "18",
    End_Mon = "04",
    Ends = "April 18",
    Tagline = "Aries season runs from  until .",
    Element = "Fire",
    Planet = "Mars",
    Modality = "Cardinal",
    Logo = require("user.logo.aries") }
