Capricorn = { Name = "Capricorn",
    Unicode = "\u{2651}",
    Start_Day = "22", 
    Start_Mon = "12", 
    Starts = "December 22",
    End_Day = "19",
    End_Mon = "01",
    Ends = "January 19",
    Tagline = "Capricorn season runs from  until .",
    Element = "Earth",
    Planet = "Saturn",
    Modality = "Cardinal",
    Logo = require("user.logo.capricorn") }
