Libra = { Name = "Libra",
    Unicode = "\u{264E}",
    Start_Day = "23", 
    Start_Mon = "09", 
    Starts = "September 23",
    End_Day = "22",
    End_Mon = "10",
    Ends = "October 22",
    Tagline = "Libra season runs from September 23 until October 22.",
    Element = "Air",
    Planet = "Venus",
    Modality = "Cardinal",
    Logo = require("user.logo.libra") }
