Scorpio = { Name = "Scorpio",
    Unicode = "\u{264F}",
    Start_Day = "23", 
    Start_Mon = "10", 
    Starts = "October 23",
    End_Day = "21",
    End_Mon = "11",
    Ends = "November 21",
    Tagline = "Scorpio season runs from October 23 until November 21.",
    Element = "Water",
    Planet = "Pluto",
    Modality = "Fixed",
    Logo = require("user.logo.scorpio") }
